### ISSUE TITLE
endpoints are based on https

### ISSUE THREAD

**Issue by OmarHent** [pambrose/prometheus-proxy#79]
Hi Team 
I see that there is failure when endpoints are using https ; how can we resolve this ?

[AgentHttpService.kt:172] - fetchScrapeUrl() sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target - https://Endpoint-host1:8082/metrics [DefaultDispatcher-worker-2]
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110)
	at io.ktor.network.tls.TLSClientHandshake.handleCertificatesAndKeys(TLSClientHandshake.kt:233)
	at io.ktor.network.tls.TLSClientHandshake.negotiate(TLSClientHandshake.kt:164)
	at io.ktor.network.tls.TLSClientHandshake$negotiate$1.invokeSuspend(TLSClientHandshake.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by pambrose** [comment]
Hi Omar, 
Do you want the client to run with a disabled SSL certificate check (yes, I know that is not cool in a production system, but it is easier for you), or do you want to set up SSL with the appropriate keys? And if you want the SSL enabled, do you want one-way or two-way authentication?
Paul

**Comment by OmarHent** [comment]
Hi @pambrose,
indeed, I want to disable SSL cert check. 
please note this is with apps prometheus endpoints not with the proxy,

**Comment by pambrose** [comment]
Okay, sounds good.

**Comment by OmarHent** [comment]
@pambrose do you have an idea what config should be applied to do this or which code to be changed?

**Comment by pambrose** [comment]
Yes, I am working on it. I am on vacation, so I have to hide my work from my wife, so it will take me a few days. :-)

**Comment by pambrose** [comment]
I created a 1.14.1 release. To disable SSL verification for agent https endpoints, you use the `TRUST_ALL_X509_CERTIFICATES` environment var, the `--trust_all_x509` CLI option, or the `agent.http.enableTrustAllX509Certificates` property.

Please let me know if that does the trick for you.

**Comment by pambrose** [comment]
Can I close this issue?

**Comment by OmarHent** [comment]
Hi @pambrose , it still fails for me - can you give sample configuration for some endpoints? also if you can provide a simple k8s image to be onboarded via yaml file, that would be great.

**Comment by pambrose** [comment]
How are you disabling SSL verification?

How is it failing?

**Comment by pambrose** [comment]
Hi @OmarHent, are you good with this issue?

**Comment by OmarHent** [comment]
Hi @pambrose  thank you for the follow up.
I believe you can close this. it is ok now.
thank you
